### ISSUE TITLE
Page doesn't load tasks if cbdebugger is running

### ISSUE THREAD

**Issue by lhoess** [ryanalbrecht/cbSchedulerViewer#2]
Hi Ryan,
Nice job with the scheduler viewer. I just discovered that if you have the **cbdebugger** installed, the tasks don't get listed on the page. Looks like **cbdebugger** adds it's content to your json response which blows up the JSON parser. Once I disabled **cbdebugger**, I could see the tasks.

**Comment by ryanalbrecht** [comment]
@lhoess 

I myself ran into this issue and to be honest I have not really put much thought in how to solve the problem. I know cbdebugger has some features to programmatically disable it. I will put this on my list of things to do! 

Thanks for posting and let me know if you run into any other issues or have some suggestions.

**Comment by ryanalbrecht** [comment]
@lhoess  This is has been fixed. Please run `box install` to get the latest version.
